import { Volunteer } from "../milestone2";

const volunteers: Volunteer[] = [
  {
    name: "Dino",
    age: 27,
    email: "Dino_Boyle@hotmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Elyse",
    age: 36,
    email: "Elyse_Abernathy70@yahoo.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Cicero",
    age: 45,
    email: "Cicero_Monahan90@yahoo.com",
    position: "volunteer",
    city: "SB",
    state: "CA",
  },
  {
    name: "Harmony",
    age: 27,
    email: "Harmony68@gmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Melody",
    age: 32,
    email: "Melody.Abbott@yahoo.com",
    position: "staff",
    city: "SF",
    state: "CA",
  },
  {
    name: "Damian",
    age: 63,
    email: "Damian.Herzog@gmail.com",
    position: "volunteer",
    city: "Denver",
    state: "CO",
  },
  {
    name: "Florence",
    age: 20,
    email: "Florence87@gmail.com",
    position: "staff",
    city: "SD",
    state: "CA",
  },
  {
    name: "Grayson",
    age: 59,
    email: "Grayson41@hotmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Alexzander",
    age: 31,
    email: "Alexzander23@hotmail.com",
    position: "staff",
    city: "LA",
    state: "CA",
  },
  {
    name: "Brycen",
    age: 14,
    email: "Brycen.Cormier26@hotmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Pearl",
    age: 34,
    email: "Pearl_Sporer@yahoo.com",
    position: "volunteer",
    city: "Denver",
    state: "CO",
  },
  {
    name: "Vern",
    age: 57,
    email: "Vern57@gmail.com",
    position: "staff",
    city: "LA",
    state: "CA",
  },
  {
    name: "Annetta",
    age: 49,
    email: "Annetta.Wilkinson93@gmail.com",
    position: "volunteer",
    city: "SF",
    state: "CA",
  },
  {
    name: "Delaney",
    age: 30,
    email: "Delaney.Kris41@gmail.com",
    position: "volunteer",
    city: "Denver",
    state: "CO",
  },
  {
    name: "Clint",
    age: 46,
    email: "Clint.Lemke@hotmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
];

const volunteers2: Volunteer[] = [
  {
    name: "Ali",
    age: 15,
    email: "Ali_Romaguera@hotmail.com",
    position: "staff",
    city: "Denver",
    state: "CO",
  },
  {
    name: "Patsy",
    age: 42,
    email: "Patsy_Hansen@hotmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Skye",
    age: 47,
    email: "Skye.Hudson80@gmail.com",
    position: "volunteer",
    city: "Seattle",
    state: "WA",
  },
  {
    name: "Kenya",
    age: 35,
    email: "Kenya_Johns8@yahoo.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Rossie",
    age: 63,
    email: "Rossie.Purdy@hotmail.com",
    position: "staff",
    city: "Seattle",
    state: "WA",
  },
  {
    name: "Liliane",
    age: 34,
    email: "Liliane_Cronin@gmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Alden",
    age: 55,
    email: "Alden.Emmerich@yahoo.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Milton",
    age: 70,
    email: "Milton_Kiehn7@yahoo.com",
    position: "volunteer",
    city: "SB",
    state: "CA",
  },
];

export { volunteers, volunteers2 };
