import { Volunteer } from "../milestone2";

const q3allAges: Volunteer[] = [
  {
    name: "Dino",
    age: 27,
    email: "Dino_Boyle@hotmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Elyse",
    age: 36,
    email: "Elyse_Abernathy70@yahoo.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Cicero",
    age: 45,
    email: "Cicero_Monahan90@yahoo.com",
    position: "volunteer",
    city: "SB",
    state: "CA",
  },
  {
    name: "Harmony",
    age: 27,
    email: "Harmony68@gmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Melody",
    age: 32,
    email: "Melody.Abbott@yahoo.com",
    position: "staff",
    city: "SF",
    state: "CA",
  },
  {
    name: "Florence",
    age: 20,
    email: "Florence87@gmail.com",
    position: "staff",
    city: "SD",
    state: "CA",
  },
  {
    name: "Grayson",
    age: 59,
    email: "Grayson41@hotmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Alexzander",
    age: 31,
    email: "Alexzander23@hotmail.com",
    position: "staff",
    city: "LA",
    state: "CA",
  },
  {
    name: "Brycen",
    age: 14,
    email: "Brycen.Cormier26@hotmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Vern",
    age: 57,
    email: "Vern57@gmail.com",
    position: "staff",
    city: "LA",
    state: "CA",
  },
  {
    name: "Annetta",
    age: 49,
    email: "Annetta.Wilkinson93@gmail.com",
    position: "volunteer",
    city: "SF",
    state: "CA",
  },
  {
    name: "Clint",
    age: 46,
    email: "Clint.Lemke@hotmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
];

const q3allAges2: Volunteer[] = [
  {
    name: "Patsy",
    age: 42,
    email: "Patsy_Hansen@hotmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Kenya",
    age: 35,
    email: "Kenya_Johns8@yahoo.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Liliane",
    age: 34,
    email: "Liliane_Cronin@gmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Alden",
    age: 55,
    email: "Alden.Emmerich@yahoo.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Milton",
    age: 70,
    email: "Milton_Kiehn7@yahoo.com",
    position: "volunteer",
    city: "SB",
    state: "CA",
  },
];

const q3Over30: Volunteer[] = [
  {
    name: "Elyse",
    age: 36,
    email: "Elyse_Abernathy70@yahoo.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Cicero",
    age: 45,
    email: "Cicero_Monahan90@yahoo.com",
    position: "volunteer",
    city: "SB",
    state: "CA",
  },
  {
    name: "Melody",
    age: 32,
    email: "Melody.Abbott@yahoo.com",
    position: "staff",
    city: "SF",
    state: "CA",
  },
  {
    name: "Grayson",
    age: 59,
    email: "Grayson41@hotmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
  {
    name: "Alexzander",
    age: 31,
    email: "Alexzander23@hotmail.com",
    position: "staff",
    city: "LA",
    state: "CA",
  },
  {
    name: "Vern",
    age: 57,
    email: "Vern57@gmail.com",
    position: "staff",
    city: "LA",
    state: "CA",
  },
  {
    name: "Annetta",
    age: 49,
    email: "Annetta.Wilkinson93@gmail.com",
    position: "volunteer",
    city: "SF",
    state: "CA",
  },
  {
    name: "Clint",
    age: 46,
    email: "Clint.Lemke@hotmail.com",
    position: "volunteer",
    city: "SLO",
    state: "CA",
  },
];

const q6update1 = {
  name: "Dino",
  age: 27,
  email: "dboyle@gmail.com",
  position: "volunteer",
  city: "SLO",
  state: "CA",
};

const q6update2 = {
  name: "Dino",
  age: 27,
  email: "Dino_Boyle@hotmail.com",
  position: "volunteer",
  city: "Seattle",
  state: "WA",
};

const q8answer1 = {
  name: "Grayson",
  age: 59,
  email: "Grayson41@hotmail.com",
  position: "staff",
  city: "SLO",
  state: "CA",
};

const q8answer2 = {
  name: "Patsy",
  age: 42,
  email: "Patsy_Hansen@hotmail.com",
  position: "staff",
  city: "SLO",
  state: "CA",
};

export {
  q3allAges,
  q3allAges2,
  q3Over30,
  q6update1,
  q6update2,
  q8answer1,
  q8answer2,
};
